[package]
name = "yun_gl"
version = "0.1.0"
edition = "2024"

[lib]
name = "yun_gl_lib"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
thiserror = "2.0.11"
downcast-rs = "2.0.1"
glium = {version = "0.36.0", features = ["winit"]}
ordered-float = "5.0.0"